# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/crayzamb/projects/DS2024

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/crayzamb/projects/DS2024

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crayzamb/projects/DS2024/CMakeFiles /home/crayzamb/projects/DS2024//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crayzamb/projects/DS2024/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main1

# Build rule for target.
main1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main1
.PHONY : main1

# fast build rule for target.
main1/fast:
	$(MAKE) $(MAKESILENT) -f exp1/CMakeFiles/main1.dir/build.make exp1/CMakeFiles/main1.dir/build
.PHONY : main1/fast

#=============================================================================
# Target rules for targets named main2

# Build rule for target.
main2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main2
.PHONY : main2

# fast build rule for target.
main2/fast:
	$(MAKE) $(MAKESILENT) -f exp2/CMakeFiles/main2.dir/build.make exp2/CMakeFiles/main2.dir/build
.PHONY : main2/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f exp3/CMakeFiles/main.dir/build.make exp3/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Vector

# Build rule for target.
Vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vector
.PHONY : Vector

# fast build rule for target.
Vector/fast:
	$(MAKE) $(MAKESILENT) -f lib/Vector/CMakeFiles/Vector.dir/build.make lib/Vector/CMakeFiles/Vector.dir/build
.PHONY : Vector/fast

#=============================================================================
# Target rules for targets named Stack

# Build rule for target.
Stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Stack
.PHONY : Stack

# fast build rule for target.
Stack/fast:
	$(MAKE) $(MAKESILENT) -f lib/Stack/CMakeFiles/Stack.dir/build.make lib/Stack/CMakeFiles/Stack.dir/build
.PHONY : Stack/fast

#=============================================================================
# Target rules for targets named List

# Build rule for target.
List: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 List
.PHONY : List

# fast build rule for target.
List/fast:
	$(MAKE) $(MAKESILENT) -f lib/List/CMakeFiles/List.dir/build.make lib/List/CMakeFiles/List.dir/build
.PHONY : List/fast

#=============================================================================
# Target rules for targets named BinTree

# Build rule for target.
BinTree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BinTree
.PHONY : BinTree

# fast build rule for target.
BinTree/fast:
	$(MAKE) $(MAKESILENT) -f lib/Bintree/CMakeFiles/BinTree.dir/build.make lib/Bintree/CMakeFiles/BinTree.dir/build
.PHONY : BinTree/fast

#=============================================================================
# Target rules for targets named Huff

# Build rule for target.
Huff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Huff
.PHONY : Huff

# fast build rule for target.
Huff/fast:
	$(MAKE) $(MAKESILENT) -f lib/Huff/CMakeFiles/Huff.dir/build.make lib/Huff/CMakeFiles/Huff.dir/build
.PHONY : Huff/fast

#=============================================================================
# Target rules for targets named Dictionary

# Build rule for target.
Dictionary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dictionary
.PHONY : Dictionary

# fast build rule for target.
Dictionary/fast:
	$(MAKE) $(MAKESILENT) -f lib/Dictionary/CMakeFiles/Dictionary.dir/build.make lib/Dictionary/CMakeFiles/Dictionary.dir/build
.PHONY : Dictionary/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BinTree"
	@echo "... Dictionary"
	@echo "... Huff"
	@echo "... List"
	@echo "... Stack"
	@echo "... Vector"
	@echo "... main"
	@echo "... main1"
	@echo "... main2"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

